"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-04 16:27:00.739580
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ur', sa.String(length=120), nullable=True),
    sa.Column('code', sa.String(length=32), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_areas'))
    )
    op.create_index('uq_areas_name_lower', 'areas', [sa.literal_column('lower(name)')], unique=True)
    op.create_table('custom_field_defs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('field_type', sa.String(length=16), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("field_type IN ('text','number','date','boolean','choice')", name=op.f('ck_custom_field_defs_field_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_custom_field_defs')),
    sa.UniqueConstraint('key', name=op.f('uq_custom_field_defs_key'))
    )
    op.create_table('packages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('display_name_ur', sa.String(length=120), nullable=True),
    sa.Column('speed_mbps', sa.SmallInteger(), nullable=True),
    sa.Column('monthly_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('cable_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('internet_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_packages_status')),
    sa.CheckConstraint('(monthly_price IS NULL OR monthly_price >= 0) AND (cable_price IS NULL OR cable_price >= 0) AND (internet_price IS NULL OR internet_price >= 0)', name=op.f('ck_packages_prices_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_packages')),
    sa.UniqueConstraint('code', name=op.f('uq_packages_code'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('code', name=op.f('uq_roles_code'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret_enc', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('uq_users_username_lower', 'users', [sa.literal_column('lower(username)')], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity', sa.String(length=64), nullable=True),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('device', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_audit_logs_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_user_at', 'audit_logs', ['user_id', 'at'], unique=False)
    op.create_table('collectors',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE')", name=op.f('ck_collectors_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_collectors_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collectors')),
    sa.UniqueConstraint('code', name=op.f('uq_collectors_code')),
    sa.UniqueConstraint('user_id', name=op.f('uq_collectors_user_id'))
    )
    op.create_table('import_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('source_system', sa.String(length=16), nullable=False),
    sa.Column('file_name', sa.String(length=300), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('parser_version', sa.String(length=32), nullable=True),
    sa.Column('summary', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_by', sa.Uuid(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('UPLOADED', 'PARSED', 'MATCHED', 'IN_REVIEW', 'APPROVED', 'IMPORTING', 'COMPLETED', 'FAILED')", name=op.f('ck_import_sessions_status')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_import_sessions_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_sessions'))
    )
    op.create_index(op.f('ix_import_sessions_file_sha256'), 'import_sessions', ['file_sha256'], unique=False)
    op.create_table('login_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('username_attempted', sa.String(length=64), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_login_history_user_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_login_history'))
    )
    op.create_table('package_aliases',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=False),
    sa.Column('alias', sa.String(length=120), nullable=False),
    sa.Column('alias_normalized', sa.String(length=120), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_package_aliases_package_id_packages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_package_aliases')),
    sa.UniqueConstraint('alias_normalized', name=op.f('uq_package_aliases_alias_normalized'))
    )
    op.create_index(op.f('ix_package_aliases_package_id'), 'package_aliases', ['package_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('family_id', sa.Uuid(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_refresh_tokens_token_hash'))
    )
    op.create_index(op.f('ix_refresh_tokens_family_id'), 'refresh_tokens', ['family_id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('streets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('name_ur', sa.String(length=120), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_streets_area_id_areas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_streets')),
    sa.UniqueConstraint('area_id', 'name', name=op.f('uq_streets_area_id'))
    )
    op.create_index(op.f('ix_streets_area_id'), 'streets', ['area_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('collector_area_assignments',
    sa.Column('collector_id', sa.Uuid(), nullable=False),
    sa.Column('area_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_collector_area_assignments_area_id_areas')),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], name=op.f('fk_collector_area_assignments_collector_id_collectors'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collector_id', 'area_id', name=op.f('pk_collector_area_assignments'))
    )
    op.create_table('customers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_code', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('full_name_ur', sa.String(length=200), nullable=True),
    sa.Column('father_name', sa.String(length=200), nullable=True),
    sa.Column('cnic', sa.Text(), nullable=True),
    sa.Column('mobile', sa.String(length=32), nullable=True),
    sa.Column('mobile_normalized', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=32), nullable=True),
    sa.Column('alt_contact', sa.String(length=64), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('address_ur', sa.Text(), nullable=True),
    sa.Column('area_id', sa.Uuid(), nullable=True),
    sa.Column('street_id', sa.Uuid(), nullable=True),
    sa.Column('house_no', sa.String(length=64), nullable=True),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED')", name=op.f('ck_customers_status')),
    sa.CheckConstraint('(lat IS NULL OR lat BETWEEN -90 AND 90) AND (lng IS NULL OR lng BETWEEN -180 AND 180)', name=op.f('ck_customers_gps_range')),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_customers_area_id_areas')),
    sa.ForeignKeyConstraint(['street_id'], ['streets.id'], name=op.f('fk_customers_street_id_streets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('customer_code', name=op.f('uq_customers_customer_code'))
    )
    op.create_index(op.f('ix_customers_area_id'), 'customers', ['area_id'], unique=False)
    op.create_index(op.f('ix_customers_mobile_normalized'), 'customers', ['mobile_normalized'], unique=False)
    op.create_table('billing_accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_billing_accounts_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billing_accounts')),
    sa.UniqueConstraint('customer_id', name=op.f('uq_billing_accounts_customer_id'))
    )
    op.create_table('collector_customer_assignments',
    sa.Column('collector_id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], name=op.f('fk_collector_customer_assignments_collector_id_collectors'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_collector_customer_assignments_customer_id_customers')),
    sa.PrimaryKeyConstraint('collector_id', 'customer_id', name=op.f('pk_collector_customer_assignments'))
    )
    op.create_table('connections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('connection_code', sa.String(length=32), nullable=False),
    sa.Column('internet_id', sa.String(length=64), nullable=True),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('package_id', sa.Uuid(), nullable=True),
    sa.Column('connection_type', sa.String(length=16), nullable=False),
    sa.Column('install_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('monthly_price_override', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('billing_day', sa.SmallInteger(), nullable=True),
    sa.Column('area_id', sa.Uuid(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("connection_type IN ('INTERNET', 'CABLE', 'COMBINED')", name=op.f('ck_connections_connection_type')),
    sa.CheckConstraint("status IN ('ACTIVE', 'SUSPENDED', 'DISCONNECTED', 'FREE', 'TRIAL')", name=op.f('ck_connections_status')),
    sa.CheckConstraint('billing_day IS NULL OR billing_day BETWEEN 1 AND 28', name=op.f('ck_connections_billing_day')),
    sa.CheckConstraint('monthly_price_override IS NULL OR monthly_price_override >= 0', name=op.f('ck_connections_override_non_negative')),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], name=op.f('fk_connections_area_id_areas')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_connections_customer_id_customers')),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_connections_package_id_packages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connections')),
    sa.UniqueConstraint('connection_code', name=op.f('uq_connections_connection_code'))
    )
    op.create_index(op.f('ix_connections_customer_id'), 'connections', ['customer_id'], unique=False)
    op.create_index(op.f('ix_connections_internet_id'), 'connections', ['internet_id'], unique=False)
    op.create_index(op.f('ix_connections_status'), 'connections', ['status'], unique=False)
    op.create_index(op.f('ix_connections_username'), 'connections', ['username'], unique=False)
    op.create_table('customer_custom_values',
    sa.Column('customer_id', sa.Uuid(), nullable=False),
    sa.Column('field_id', sa.Uuid(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_custom_values_customer_id_customers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['field_id'], ['custom_field_defs.id'], name=op.f('fk_customer_custom_values_field_id_custom_field_defs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('customer_id', 'field_id', name=op.f('pk_customer_custom_values'))
    )
    op.create_table('connection_service_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('service', sa.String(length=16), nullable=False),
    sa.Column('package_id', sa.Uuid(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.CheckConstraint("service IN ('CABLE','INTERNET')", name=op.f('ck_connection_service_lines_service')),
    sa.CheckConstraint('price IS NULL OR price >= 0', name=op.f('ck_connection_service_lines_price_non_negative')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_connection_service_lines_connection_id_connections'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['packages.id'], name=op.f('fk_connection_service_lines_package_id_packages')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connection_service_lines')),
    sa.UniqueConstraint('connection_id', 'service', name=op.f('uq_connection_service_lines_connection_id'))
    )
    op.create_index(op.f('ix_connection_service_lines_connection_id'), 'connection_service_lines', ['connection_id'], unique=False)
    op.create_table('external_refs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('system', sa.String(length=16), nullable=False),
    sa.Column('ref_type', sa.String(length=16), nullable=False),
    sa.Column('value', sa.String(length=128), nullable=False),
    sa.CheckConstraint("ref_type IN ('ID', 'INTERNET_ID', 'USERNAME')", name=op.f('ck_external_refs_ref_type')),
    sa.CheckConstraint("system IN ('WASOOLI', 'ZALPRO', 'MIKROTIK')", name=op.f('ck_external_refs_system')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_external_refs_connection_id_connections'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_refs')),
    sa.UniqueConstraint('system', 'ref_type', 'value', name=op.f('uq_external_refs_system'))
    )
    op.create_index(op.f('ix_external_refs_connection_id'), 'external_refs', ['connection_id'], unique=False)
    op.create_table('import_rows',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('row_index', sa.Integer(), nullable=False),
    sa.Column('raw_cells', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issues', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('match_candidates', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.Column('result_customer_id', sa.Uuid(), nullable=True),
    sa.Column('result_connection_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('NEW', 'DUPLICATE', 'UPDATED', 'ERROR', 'REVIEW', 'IMPORTED', 'SKIPPED')", name=op.f('ck_import_rows_status')),
    sa.ForeignKeyConstraint(['result_connection_id'], ['connections.id'], name=op.f('fk_import_rows_result_connection_id_connections')),
    sa.ForeignKeyConstraint(['result_customer_id'], ['customers.id'], name=op.f('fk_import_rows_result_customer_id_customers')),
    sa.ForeignKeyConstraint(['session_id'], ['import_sessions.id'], name=op.f('fk_import_rows_session_id_import_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_rows')),
    sa.UniqueConstraint('session_id', 'row_index', name=op.f('uq_import_rows_session_id'))
    )
    op.create_index(op.f('ix_import_rows_session_id'), 'import_rows', ['session_id'], unique=False)
    op.create_index(op.f('ix_import_rows_status'), 'import_rows', ['status'], unique=False)
    op.create_table('invoices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_number', sa.String(length=32), nullable=False),
    sa.Column('billing_account_id', sa.Uuid(), nullable=False),
    sa.Column('period', sa.Date(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('due_date >= issue_date', name=op.f('ck_invoices_due_after_issue')),
    sa.CheckConstraint('total >= 0', name=op.f('ck_invoices_total_non_negative')),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], name=op.f('fk_invoices_billing_account_id_billing_accounts')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_invoices_created_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoices')),
    sa.UniqueConstraint('invoice_number', name=op.f('uq_invoices_invoice_number'))
    )
    op.create_index('ix_invoices_account_due', 'invoices', ['billing_account_id', 'due_date'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('billing_account_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('entry_type', sa.String(length=24), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ref_type', sa.String(length=24), nullable=True),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('posted_by', sa.Uuid(), nullable=True),
    sa.Column('reverses_entry_id', sa.Uuid(), nullable=True),
    sa.CheckConstraint("entry_type IN ('CHARGE', 'DISCOUNT', 'PAYMENT', 'PAYMENT_REVERSAL', 'ADJUSTMENT', 'REFUND')", name=op.f('ck_ledger_entries_entry_type')),
    sa.CheckConstraint('amount <> 0', name=op.f('ck_ledger_entries_amount_non_zero')),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], name=op.f('fk_ledger_entries_billing_account_id_billing_accounts')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_ledger_entries_connection_id_connections')),
    sa.ForeignKeyConstraint(['posted_by'], ['users.id'], name=op.f('fk_ledger_entries_posted_by_users')),
    sa.ForeignKeyConstraint(['reverses_entry_id'], ['ledger_entries.id'], name=op.f('fk_ledger_entries_reverses_entry_id_ledger_entries')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ledger_entries')),
    sa.UniqueConstraint('reverses_entry_id', name=op.f('uq_ledger_entries_reverses_entry_id'))
    )
    op.create_index(op.f('ix_ledger_entries_billing_account_id'), 'ledger_entries', ['billing_account_id'], unique=False)
    op.create_index('ix_ledger_entries_ref', 'ledger_entries', ['ref_type', 'ref_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('billing_account_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('collector_id', sa.Uuid(), nullable=True),
    sa.Column('client_txn_id', sa.String(length=64), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('void_reason', sa.Text(), nullable=True),
    sa.Column('voided_by', sa.Uuid(), nullable=True),
    sa.Column('voided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("method IN ('CASH', 'COLLECTOR_CASH', 'BANK', 'JAZZCASH', 'EASYPAISA', 'CARD', 'QR')", name=op.f('ck_payments_method')),
    sa.CheckConstraint("status IN ('POSTED', 'VOID', 'NEEDS_REVIEW')", name=op.f('ck_payments_status')),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payments_amount_positive')),
    sa.ForeignKeyConstraint(['billing_account_id'], ['billing_accounts.id'], name=op.f('fk_payments_billing_account_id_billing_accounts')),
    sa.ForeignKeyConstraint(['collector_id'], ['collectors.id'], name=op.f('fk_payments_collector_id_collectors')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_payments_connection_id_connections')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_payments_created_by_users')),
    sa.ForeignKeyConstraint(['voided_by'], ['users.id'], name=op.f('fk_payments_voided_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    sa.UniqueConstraint('collector_id', 'client_txn_id', name=op.f('uq_payments_collector_id'))
    )
    op.create_index(op.f('ix_payments_billing_account_id'), 'payments', ['billing_account_id'], unique=False)
    op.create_index(op.f('ix_payments_collector_id'), 'payments', ['collector_id'], unique=False)
    op.create_table('import_row_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('row_id', sa.Uuid(), nullable=False),
    sa.Column('decision', sa.String(length=24), nullable=False),
    sa.Column('edited_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decided_by', sa.Uuid(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('IMPORT', 'SKIP', 'UPDATE_EXISTING', 'CREATE_SEPARATE', 'MANUAL_EDIT')", name=op.f('ck_import_row_decisions_decision')),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], name=op.f('fk_import_row_decisions_decided_by_users')),
    sa.ForeignKeyConstraint(['row_id'], ['import_rows.id'], name=op.f('fk_import_row_decisions_row_id_import_rows'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_row_decisions'))
    )
    op.create_index(op.f('ix_import_row_decisions_row_id'), 'import_row_decisions', ['row_id'], unique=False)
    op.create_table('invoice_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=True),
    sa.Column('charge_type', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint("(charge_type = 'DISCOUNT' AND amount <= 0) OR (charge_type <> 'DISCOUNT' AND amount >= 0)", name=op.f('ck_invoice_lines_sign_matches_type')),
    sa.CheckConstraint("charge_type IN ('INTERNET', 'CABLE', 'INSTALLATION', 'RECONNECTION', 'EQUIPMENT', 'LATE_FEE', 'OTHER', 'DISCOUNT')", name=op.f('ck_invoice_lines_charge_type')),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], name=op.f('fk_invoice_lines_connection_id_connections')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_invoice_lines_invoice_id_invoices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invoice_lines'))
    )
    op.create_index(op.f('ix_invoice_lines_invoice_id'), 'invoice_lines', ['invoice_id'], unique=False)
    op.create_table('payment_allocations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('invoice_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.CheckConstraint('amount > 0', name=op.f('ck_payment_allocations_amount_positive')),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], name=op.f('fk_payment_allocations_invoice_id_invoices')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_payment_allocations_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payment_allocations'))
    )
    op.create_index(op.f('ix_payment_allocations_invoice_id'), 'payment_allocations', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_payment_allocations_payment_id'), 'payment_allocations', ['payment_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_number', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('issued_by', sa.Uuid(), nullable=True),
    sa.CheckConstraint("status IN ('ISSUED', 'VOID')", name=op.f('ck_receipts_status')),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], name=op.f('fk_receipts_issued_by_users')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_receipts_payment_id_payments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_receipts')),
    sa.UniqueConstraint('payment_id', name=op.f('uq_receipts_payment_id')),
    sa.UniqueConstraint('receipt_number', name=op.f('uq_receipts_receipt_number'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipts')
    op.drop_index(op.f('ix_payment_allocations_payment_id'), table_name='payment_allocations')
    op.drop_index(op.f('ix_payment_allocations_invoice_id'), table_name='payment_allocations')
    op.drop_table('payment_allocations')
    op.drop_index(op.f('ix_invoice_lines_invoice_id'), table_name='invoice_lines')
    op.drop_table('invoice_lines')
    op.drop_index(op.f('ix_import_row_decisions_row_id'), table_name='import_row_decisions')
    op.drop_table('import_row_decisions')
    op.drop_index(op.f('ix_payments_collector_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_billing_account_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_ledger_entries_ref', table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_billing_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index('ix_invoices_account_due', table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_import_rows_status'), table_name='import_rows')
    op.drop_index(op.f('ix_import_rows_session_id'), table_name='import_rows')
    op.drop_table('import_rows')
    op.drop_index(op.f('ix_external_refs_connection_id'), table_name='external_refs')
    op.drop_table('external_refs')
    op.drop_index(op.f('ix_connection_service_lines_connection_id'), table_name='connection_service_lines')
    op.drop_table('connection_service_lines')
    op.drop_table('customer_custom_values')
    op.drop_index(op.f('ix_connections_username'), table_name='connections')
    op.drop_index(op.f('ix_connections_status'), table_name='connections')
    op.drop_index(op.f('ix_connections_internet_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_customer_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_table('collector_customer_assignments')
    op.drop_table('billing_accounts')
    op.drop_index(op.f('ix_customers_mobile_normalized'), table_name='customers')
    op.drop_index(op.f('ix_customers_area_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_table('collector_area_assignments')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_streets_area_id'), table_name='streets')
    op.drop_table('streets')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_family_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_package_aliases_package_id'), table_name='package_aliases')
    op.drop_table('package_aliases')
    op.drop_table('login_history')
    op.drop_index(op.f('ix_import_sessions_file_sha256'), table_name='import_sessions')
    op.drop_table('import_sessions')
    op.drop_table('collectors')
    op.drop_index('ix_audit_logs_user_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('uq_users_username_lower', table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('packages')
    op.drop_table('custom_field_defs')
    op.drop_index('uq_areas_name_lower', table_name='areas')
    op.drop_table('areas')
    # ### end Alembic commands ###
